spring.application.name=sndf-backend

spring.datasource.url=jdbc:mysql://localhost:3306/sndf_db
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


#jwt.secret=SNDF_SUPER_SECURE_SECRET_KEY_1234567890_ABCDEFGHIJKLMNOPQRSTUVWXYZ
#jwt.expiration=900000



jwt.secret=7@fK9#Lm2!Qp$8ZxR5vN1wXcT6yUoA3bFhJkL0M^pD4sG7hJ!2Qx
jwt.expiration=900000

frontend.url=http://localhost:5173

